### ISSUE TITLE
dataset issues and concept.txt file

### ISSUE THREAD

**Issue by antonie-z** [sandareka/CCNN#1]
Hello, thank you for sharing the code. I would like to know how you split the train and test in the data folder and I can't find the concept.txt in the data folder. Thank you!

**Comment by sandareka** [comment]
Hi @antonie-z,

For the CUB dataset, I used the standard train and test split provided by the dataset provider - http://www.vision.caltech.edu/datasets/cub_200_2011/
concept.txt is now available at https://github.com/sandareka/CCNN/tree/main/tensorflow_implementation/data.

Thanks.
